import { Lead, PropertyUnit, Project, Building, Booking, LeadNote, Profile } from './types/crm';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-admin-1',
    email: 'admin@realstate.com',
    full_name: 'Sarah Connor (Sales Director)',
    role: 'admin',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-rep-1',
    email: 'john.doe@realstate.com',
    full_name: 'John Doe (Senior Executive)',
    role: 'sales_rep',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-rep-2',
    email: 'rachel.green@realstate.com',
    full_name: 'Rachel Green (Property Consultant)',
    role: 'sales_rep',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'The Grand Horizon',
    location: '104 Oceanfront Boulevard',
    city: 'Marina Bay',
    description: 'Ultra-luxury waterfront residences with panoramic ocean views, private marina access, and infinity decks.',
    status: 'Under Construction',
    featured_image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    name: 'Silverstone Heights',
    location: '45 Financial District Way',
    city: 'Downtown Core',
    description: 'Architectural marvel featuring smart home automation, rooftop helipad, and executive co-working club.',
    status: 'Ready to Move',
    featured_image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    name: 'Emerald Eco Sanctuary',
    location: '12 Greenwood Ridge',
    city: 'Pine Valley',
    description: 'Bespoke biophilic estate villas powered completely by solar micro-grids and surrounded by private nature trails.',
    status: 'Planning',
    featured_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_BUILDINGS: Building[] = [
  {
    id: 'bldg-1',
    project_id: 'proj-1',
    name: 'Azure Tower (Tower A)',
    total_floors: 24,
    created_at: new Date().toISOString(),
  },
  {
    id: 'bldg-2',
    project_id: 'proj-1',
    name: 'Coral Tower (Tower B)',
    total_floors: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'bldg-3',
    project_id: 'proj-2',
    name: 'Pinnacle Skytower',
    total_floors: 32,
    created_at: new Date().toISOString(),
  },
  {
    id: 'bldg-4',
    project_id: 'proj-3',
    name: 'Phase 1 - Forest Villas',
    total_floors: 2,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_UNITS: PropertyUnit[] = [
  // Tower A - Azure
  {
    id: 'unit-101',
    building_id: 'bldg-1',
    unit_number: 'A-101',
    type: '1BHK',
    floor: 1,
    area_sqft: 750,
    price: 245000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-102',
    building_id: 'bldg-1',
    unit_number: 'A-102',
    type: '2BHK',
    floor: 1,
    area_sqft: 1150,
    price: 385000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-201',
    building_id: 'bldg-1',
    unit_number: 'A-201',
    type: '2BHK',
    floor: 2,
    area_sqft: 1200,
    price: 395000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-401',
    building_id: 'bldg-1',
    unit_number: 'A-401',
    type: '3BHK',
    floor: 4,
    area_sqft: 1850,
    price: 630000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-1201',
    building_id: 'bldg-1',
    unit_number: 'A-1201',
    type: '3BHK',
    floor: 12,
    area_sqft: 1950,
    price: 720000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-2401',
    building_id: 'bldg-1',
    unit_number: 'A-PH24',
    type: 'Penthouse',
    floor: 24,
    area_sqft: 3400,
    price: 1480000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Tower B - Coral
  {
    id: 'unit-b101',
    building_id: 'bldg-2',
    unit_number: 'B-101',
    type: '1BHK',
    floor: 1,
    area_sqft: 720,
    price: 235000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-b301',
    building_id: 'bldg-2',
    unit_number: 'B-301',
    type: '2BHK',
    floor: 3,
    area_sqft: 1180,
    price: 390000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-b501',
    building_id: 'bldg-2',
    unit_number: 'B-501',
    type: '3BHK',
    floor: 5,
    area_sqft: 1780,
    price: 595000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Pinnacle Skytower
  {
    id: 'unit-p1001',
    building_id: 'bldg-3',
    unit_number: 'P-1001',
    type: '2BHK',
    floor: 10,
    area_sqft: 1250,
    price: 490000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-p2001',
    building_id: 'bldg-3',
    unit_number: 'P-2001',
    type: '3BHK',
    floor: 20,
    area_sqft: 2100,
    price: 890000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-pph32',
    building_id: 'bldg-3',
    unit_number: 'P-PH32',
    type: 'Penthouse',
    floor: 32,
    area_sqft: 4200,
    price: 2150000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Eco Sanctuary Villas
  {
    id: 'unit-v01',
    building_id: 'bldg-4',
    unit_number: 'Villa Pine 1',
    type: 'Villa',
    floor: 1,
    area_sqft: 3800,
    price: 1320000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-v02',
    building_id: 'bldg-4',
    unit_number: 'Villa Pine 2',
    type: 'Villa',
    floor: 1,
    area_sqft: 4600,
    price: 1680000,
    status: 'Available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    first_name: 'Alexander',
    last_name: 'Wright',
    email: 'alex.wright@executive.com',
    phone: '+1 (555) 234-5678',
    budget_min: 350000,
    budget_max: 450000,
    preferred_type: '2BHK',
    source: 'Website',
    stage: 'New',
    assigned_to: 'user-rep-1',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    first_name: 'Sophia',
    last_name: 'Chen',
    email: 'sophia.chen@techglobal.io',
    phone: '+1 (555) 345-6789',
    budget_min: 600000,
    budget_max: 800000,
    preferred_type: '3BHK',
    source: 'Walk-in',
    stage: 'Contacted',
    assigned_to: 'user-rep-1',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    first_name: 'Marcus',
    last_name: 'Vance',
    email: 'marcus.vance@capitalgroup.com',
    phone: '+1 (555) 456-7890',
    budget_min: 1400000,
    budget_max: 2200000,
    preferred_type: 'Penthouse',
    source: 'Referral',
    stage: 'Site Visit',
    assigned_to: 'user-rep-2',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-4',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena.rostova@designworks.com',
    phone: '+1 (555) 567-8901',
    budget_min: 500000,
    budget_max: 750000,
    preferred_type: '3BHK',
    source: 'Social Media',
    stage: 'Interested',
    assigned_to: 'user-rep-2',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-5',
    first_name: 'David',
    last_name: 'Miller',
    email: 'david.miller@apexinvest.org',
    phone: '+1 (555) 678-9012',
    budget_min: 380000,
    budget_max: 420000,
    preferred_type: '2BHK',
    source: 'Real Estate Portal',
    stage: 'Negotiation',
    assigned_to: 'user-rep-1',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-6',
    first_name: 'Liam',
    last_name: 'O’Connor',
    email: 'liam.oc@ventures.com',
    phone: '+1 (555) 789-0123',
    budget_min: 200000,
    budget_max: 260000,
    preferred_type: '1BHK',
    source: 'Cold Call',
    stage: 'Lost',
    assigned_to: 'user-rep-2',
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_NOTES: LeadNote[] = [
  {
    id: 'note-1',
    lead_id: 'lead-1',
    author_id: 'user-rep-1',
    note: 'Inquired about ocean-facing balconies on middle floors.',
    follow_up_date: new Date(Date.now() + 24 * 3600 * 1000 * 1).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 1).toISOString(),
  },
  {
    id: 'note-2',
    lead_id: 'lead-2',
    author_id: 'user-rep-1',
    note: 'Completed intro call. Sophia wants a 3BHK with parking space. Requested brochure sent via email.',
    follow_up_date: new Date(Date.now() + 24 * 3600 * 1000 * 2).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 2).toISOString(),
  },
  {
    id: 'note-3',
    lead_id: 'lead-3',
    author_id: 'user-rep-2',
    note: 'Confirmed Site Visit for Saturday 11:00 AM at Pinnacle Skytower Penthouse.',
    follow_up_date: new Date(Date.now() + 24 * 3600 * 1000 * 3).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 3).toISOString(),
  },
  {
    id: 'note-4',
    lead_id: 'lead-4',
    author_id: 'user-rep-2',
    note: 'Client loved the floor layout of A-401. Reviewing financing options with bank.',
    follow_up_date: new Date(Date.now() + 24 * 3600 * 1000 * 2).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 4).toISOString(),
  },
  {
    id: 'note-5',
    lead_id: 'lead-5',
    author_id: 'user-rep-1',
    note: 'Offered special rate on A-201. Buyer agreed on $390,000 price point. Preparing paperwork.',
    follow_up_date: new Date().toISOString(), // Today!
    created_at: new Date(Date.now() - 24 * 3600 * 1000 * 1).toISOString(),
  },
];
